spring.application.name=demo
# Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=hospital_db
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate (Otomatik Tablo Oluşturma) Ayarları
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update